### ISSUE TITLE
Make a GitHub release

### ISSUE THREAD

**Issue by apcamargo** [yarrow/zet#1]
I've been using `zet` for some time now and I wanted to add it to Conda and Homebrew, but they require the package to have a `tar.gz` release.

**Comment by yarrow** [comment]
Thanks! I will look into that. It's not something I've done before, so I may take a while

**Comment by apcamargo** [comment]
Thanks! In case you want to check, here's the [official documentation](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) for how to make a release.

**Comment by yarrow** [comment]
Thanks! That helped a lot. I've made the release. I haven't included any binaries, though. Does a source-code-only release meet your need?

**Comment by apcamargo** [comment]
Yes. That's exactly what I needed.

Thanks!

**Comment by yarrow** [comment]
Excellent! I will close the issue.

**Comment by apcamargo** [comment]
Well, Homebrew won't let me add the package because it's not "notable" enough (needs more starts, watchers, forks). I hope this gets popular with time!

**Comment by yarrow** [comment]
Thanks! Now that I have proof that somebody other than me is using it, I'm intending to clean it up a bit and then announce its existence. (Cleaning up — currently it will break lines incorrectly for UTF-16, so it's not safe to use on Windows. I need to change that. Or at least tell people "Don't use on Windows!" ^_^)

**Comment by apcamargo** [comment]
That's great! It seems that the project has gained some visibility too :)

**Comment by yarrow** [comment]
I've updated Zet to handle UTF-16 correctly, and created a 0.2.0 release with binaries for Linux, Mac, and Windows. I've announced on [users.rustlang.org](https://users.rust-lang.org/t/zet-take-the-union-intersection-etc-of-files/61952) and [r/rust](https://www.reddit.com/r/rust/comments/oedhm9/zet_take_the_union_intersection_etc_of_files/).

**Comment by apcamargo** [comment]
[Just added it to Homebrew](https://formulae.brew.sh/formula/zet).

**Comment by yarrow** [comment]
> [Just added it to Homebrew](https://formulae.brew.sh/formula/zet).

Excellent! Thank you!
