### ISSUE TITLE
Packaging Query: version 0.2.5 missing from crates.io

### ISSUE THREAD

**Issue by AulonSal** [yarrow/zet#6]
Is there a reason https://github.com/yarrow/zet/releases/tag/0.2.5 is not on crates.io(https://crates.io/crates/zet)?

**Comment by yarrow** [comment]
I've been having trouble packaging it as a binary release, and haven't had time to puzzle out why. I'd like to release binaries at the same time I update crates.io

**Comment by SamuelSwartzberg** [comment]
Seems that something went wrong with the bstr dependency in 0.2.6?
```
    Updating crates.io index
  Downloaded zet v0.2.6
  Downloaded 1 crate (26.4 KB) in 0.55s
  Installing zet v0.2.6
error: failed to compile `zet v0.2.6`, intermediate artifacts can be found at `/Users/sam/.tmp/cargo-installCB9eTY`

Caused by:
  failed to select a version for the requirement `bstr = "^1.1.0"`
  candidate versions found which didn't match: 0.2.17, 0.2.16, 0.2.15, ...
  location searched: crates.io index
  required by package `zet v0.2.6`
```

**Comment by yarrow** [comment]
> Seems that something went wrong with the bstr dependency in 0.2.6?
>   failed to select a version for the requirement `bstr = "^1.1.0"`
>   candidate versions found which didn't match: 0.2.17, 0.2.16, 0.2.15, ...

This seems to be saying it couldn't find `bstr 1.1.0` (or `1.x.y` where `x >= 1`).  But `bstr 1.1.0` does exist (as does `bstr 1.2.0`). Any chance that the CARGO_NET_OFFLINE  environment variable is set, or net.offline in a config.toml somewhere?

**Comment by SamuelSwartzberg** [comment]
After a bit of research and it turned out to be that rust itself was out of date, requiring >= 1.60, and me having 1.59. Sorry for troubling you with a local installation issue!
