### ISSUE TITLE
Options `--count` and `-c` differ in behaviour

### ISSUE THREAD

**Issue by sudo-nice** [yarrow/zet#9]
Please, consider the file `cat some_file`:

    foo
    bar
    foo

Now, running `zet union some_file --count`, we get (as expected):

    2 foo
    1 bar

But running `zet union some_file -c`, we get unexpectedly different result:

    1 foo
    1 bar

Judging by the description, these options should produce the same result. I've tested zet 1.0.0.

**Comment by yarrow** [comment]
Yes, this is an error. Fixed in 2.0 (which isn't out yet — and is only 2.0 because fixing the error will result in changed behavior!)

**Comment by yarrow** [comment]
Version 2.0.1, which fixes this, has been released
